#!/usr/bin/env python3
"""
Plot IO vs Compute Latency from CSV data (excluding TFFT)

This script reads the profiler_io_compute_latency.csv file generated by
Llama_analysis.py with --enable-profiler flag and recreates the
latency_comparison_no_ttft.png graph.

Usage:
    python plot_io_compute_latency.py [--csv PATH] [--output PATH]
"""

import argparse
import csv
import numpy as np
import matplotlib.pyplot as plt
import sys
import os


def load_csv_data(csv_path):
    """Load IO and Compute data from CSV file."""
    token_numbers = []
    compute_totals = []
    io_totals = []
    compute_stds = []
    io_stds = []

    with open(csv_path, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            token_numbers.append(int(row['Token_Number']))
            compute_totals.append(float(row['Total_Compute_ms']))
            io_totals.append(float(row['Total_IO_ms']))
            compute_stds.append(float(row['Compute_StdDev']))
            io_stds.append(float(row['IO_StdDev']))

    return (np.array(token_numbers), np.array(compute_totals),
            np.array(io_totals), np.array(compute_stds), np.array(io_stds))


def plot_latency_no_tfft(token_numbers, compute_totals, io_totals,
                         compute_stds, io_stds, output_path, n_layers=16):
    """
    Plot IO vs Compute latency excluding TFFT (first token).

    Args:
        token_numbers: Array of token numbers
        compute_totals: Array of total compute latencies
        io_totals: Array of total IO latencies
        compute_stds: Array of compute standard deviations across layers
        io_stds: Array of IO standard deviations across layers
        output_path: Path to save the output plot
        n_layers: Number of layers (default 16 for Llama models)
    """
    # Exclude TFFT (first token)
    token_numbers_no_tfft = token_numbers[1:]
    compute_no_tfft = compute_totals[1:]
    io_no_tfft = io_totals[1:]
    compute_std_no_tfft = compute_stds[1:]
    io_std_no_tfft = io_stds[1:]

    # Calculate means
    compute_mean = np.mean(compute_no_tfft)
    io_mean = np.mean(io_no_tfft)

    # Create figure
    fig, ax = plt.subplots(figsize=(14, 8))

    # Plot Compute line with error bounds
    ax.plot(token_numbers_no_tfft, compute_no_tfft, '-',
            linewidth=2.0, color='#2E86AB', alpha=0.9)
    ax.fill_between(token_numbers_no_tfft,
                     compute_no_tfft - compute_std_no_tfft * np.sqrt(n_layers),
                     compute_no_tfft + compute_std_no_tfft * np.sqrt(n_layers),
                     alpha=0.25, color='#2E86AB',
                     label=f'Compute (σ={np.mean(compute_std_no_tfft):.2f}ms)')

    # Plot IO line with error bounds
    ax.plot(token_numbers_no_tfft, io_no_tfft, '-',
            linewidth=2.0, color='#A23B72', alpha=0.9)
    ax.fill_between(token_numbers_no_tfft,
                     io_no_tfft - io_std_no_tfft * np.sqrt(n_layers),
                     io_no_tfft + io_std_no_tfft * np.sqrt(n_layers),
                     alpha=0.25, color='#A23B72',
                     label=f'IO (σ={np.mean(io_std_no_tfft):.2f}ms)')

    # Labels and styling
    ax.set_xlabel('Number of Processed Tokens (Prefill + Decode, TTFT Excluded)')
    ax.set_ylabel('Aggregated Latency Across Layers (ms)')
    ax.set_title('Error-Bound Analysis of IO and Compute Latency Across Layers (TTFT Excluded)')
    ax.grid(True, alpha=0.3)
    ax.legend(loc='best')

    plt.tight_layout()

    # Save as PNG and PDF
    png_path = output_path
    pdf_path = output_path.replace('.png', '.pdf')

    plt.savefig(png_path, dpi=300, bbox_inches='tight')
    plt.savefig(pdf_path, bbox_inches='tight')

    print(f"✓ Plot saved to: {png_path}")
    print(f"✓ Plot saved to: {pdf_path}")

    print(f"\nStatistics (TTFT excluded):")
    print(f"  Compute - Mean: {compute_mean:.2f}ms")
    print(f"  IO - Mean: {io_mean:.2f}ms")
    print(f"  Total tokens plotted: {len(token_numbers_no_tfft)}")

    plt.close(fig)


def main():
    parser = argparse.ArgumentParser(
        description='Plot IO vs Compute latency from CSV data (excluding TFFT)'
    )
    parser.add_argument('--csv', type=str,
                       default='profiler_io_compute_latency.csv',
                       help='Path to the CSV file (default: profiler_io_compute_latency.csv)')
    parser.add_argument('--output', type=str,
                       default='latency_comparison_no_ttft_from_csv.png',
                       help='Output plot filename (default: latency_comparison_no_ttft_from_csv.png)')
    parser.add_argument('--n-layers', type=int, default=16,
                       help='Number of layers in the model (default: 16)')

    args = parser.parse_args()

    # Check if CSV file exists
    if not os.path.exists(args.csv):
        print(f"Error: CSV file not found: {args.csv}")
        print(f"\nPlease run Llama_analysis.py with --enable-profiler flag first:")
        print(f"  python Llama_analysis.py --enable-profiler")
        sys.exit(1)

    print(f"Loading data from: {args.csv}")
    token_numbers, compute_totals, io_totals, compute_stds, io_stds = load_csv_data(args.csv)

    print(f"Loaded {len(token_numbers)} tokens")
    print(f"TFFT (Token 1) - Compute: {compute_totals[0]:.2f}ms, IO: {io_totals[0]:.2f}ms")

    # Generate plot
    plot_latency_no_tfft(token_numbers, compute_totals, io_totals,
                         compute_stds, io_stds, args.output, args.n_layers)


if __name__ == '__main__':
    main()
